name: ipyradiant

channels:
  - conda-forge
  - msys2
  - nodefaults

dependencies:
  - black
  - bqplot
  - conda-build
  - datashader
  - doit
  - flake8
  - ipycytoscape
  - ipywidgets
  - isort <5
  - jupyter_bokeh
  - jupyterlab ==2.2.0
  - mypy
  - networkx
  - nodejs >=12,<13.0.0a0
  - nomkl
  - pyld
  - pylint
  - pyshacl
  - python >=3.7,<3.8.0a0
  - qgrid
  - rdflib-jsonld
