name: ipyradiant

channels:
  - conda-forge
  - msys2

dependencies:
  - bqplot
  - datashader
  - ipycytoscape
  - ipywidgets
  - jupyter_bokeh
  - jupyterlab ==2.2.0
  - networkx
  - nodejs >=12,<13.0.0a0
  - numpy
  - pip
  - pyld
  - pyshacl
  - python >=3.6
  - qgrid
  - rdflib-jsonld
