{% set name = "ipyradiant" %}
{% set version = "0.1.0" %}
{% set dist = name ~ "-" ~ version %}
{% set fname = dist ~ ".tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../dist/{{ fname }}

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -c "__import__('tarfile').open('{{ fname }}').extractall()"
    - cd {{ dist }} && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - ipywidgets
    - pandas
    - qgrid
    - rdflib
    - python

test:
  requires:
    - pip
  imports:
    - ipyradiant
  commands:
    - python -m pip check

about:
  home: https://github.com/zwelz3/ipyradiant
  license: BSD-3-Clause
  license_family: MIT
  license_file: {{ dist }}/LICENSE  # [unix]
  license_file: {{ dist }}\LICENSE  # [win]
  summary: Jupyter Widgets for working with RDF graphs
